# docker-compose.yml
version: '3.9'

services:
  discord-bot:
      build: .
      restart: unless-stopped

      volumes:
        - ./logs:/data/logs

      # Consider importing mongodb and setting the volume there for persistency